### ISSUE TITLE
Autorise les votes multiples // Allows multiples votes.

### ISSUE THREAD

**Issue by jemdev** [oceanBigOne/MajorityJudgment#8]
Ce système ne semble pas filtrer la possibilité de revenir plusieurs fois sur la page pour voter à nouveau. Le résultat a donc toutes les chances d'être complètement faux.
//
This system does not seem to filter the possibility of returning several times to the page to vote again. The result is therefore likely to be completely wrong.

**Comment by oceanBigOne** [comment]
Bonjour,

Merci pour votre retour. Ce projet n'est qu'un outil de dépouillement de votes à destination des développeurs PHP (il n'y a pas de "pages"). 

Je pense que vous parlez de ce dépôt : https://github.com/MieuxVoter/jm

Et effectivement, vous avez complètement raison. C'est d’ailleurs précisé dès la page d'accueil :

-----
**Avertissement**

Cette page n'est pas conçue pour des votes à fort enjeux car aucune vérification d'identité des votants n'est effectuée. Un participant peut voter autant de fois qu'il le souhaite. Il est cependant possible de savoir combien de participations ont été enregistrées à la fin d'un vote. Il est donc possible pour un groupe de personnes de déceler un problème, si il y a plus de participations que de personnes.

-------

Nous travaillons actuellement avec l'association Mieux Voter sur une plateforme permettant, à terme, de faire des votes un peu plus sécurisés. Cette première version sera alors abandonnée.
